version: '3'
services:

  #
  # janus-gateway
  #
  janus-gateway:
    image: canyan/janus-gateway:latest
    command: ["/usr/local/bin/janus", "-F", "/usr/local/etc/janus"]
    ports:
      - "8078:8088"
      - "8079:8089"
      - "8879:8889"
      - "8010:8000"
      - "7078:7088"
      - "7079:7089"
    volumes:
      - ./etc/janus/:/opt/janus/etc/janus/
      - ./config/janus:/opt/janus/lib/janus/
    restart: always
